version: '3.7'
services:
  alpine:
    container_name: dc-boilerplate-alpine
    build:
      context: alpine
      args:
        UID: ${DOCKER_UID:-1000}
        GID: ${DOCKER_GID:-1000}
    volumes:
      - ./:/usr/src/app

  centos:
    container_name: dc-boilerplate-centos
    restart: always
    build:
      context: centos
      args:
        UID: ${DOCKER_UID:-1000}
        GID: ${DOCKER_GID:-1000}
    volumes:
      - ./:/usr/src/app

  debian:
    container_name: dc-boilerplate-debian
    restart: always
    build:
      context: debian
      args:
        UID: ${DOCKER_UID:-1000}
        GID: ${DOCKER_GID:-1000}
    volumes:
      - ./:/usr/src/app

  fedora:
    container_name: dc-boilerplate-fedora
    restart: always
    build:
      context: fedora
      args:
        UID: ${DOCKER_UID:-1000}
        GID: ${DOCKER_GID:-1000}
    volumes:
      - ./:/usr/src/app

  ubuntu:
    container_name: dc-boilerplate-ubuntu
    restart: always
    build:
      context: ubuntu
      args:
        UID: ${DOCKER_UID:-1000}
        GID: ${DOCKER_GID:-1000}
    volumes:
      - ./:/usr/src/app