version: '3.7'
services:
  ubuntu:
    container_name: dc-boilerplate-ubuntu
    restart: always
    build:
      context: ubuntu
      args:
        UID: ${USER_ID:-1000}
        GID: ${GROUP_ID:-1000}
    working_dir: /var/www/dc-boilerplate
    volumes:
      - ../:/var/www/dc-boilerplate
  
  fedora:
    container_name: dc-boilerplate-fedora
    restart: always
    build:
      context: fedora
      args:
        UID: ${USER_ID:-1000}
        GID: ${GROUP_ID:-1000}
    working_dir: /var/www/dc-boilerplate
    volumes:
      - ../:/var/www/dc-boilerplate
  
  debian:
    container_name: dc-boilerplate-debian
    restart: always
    build:
      context: debian
      args:
        UID: ${USER_ID:-1000}
        GID: ${GROUP_ID:-1000}
    working_dir: /var/www/dc-boilerplate
    volumes:
      - ../:/var/www/dc-boilerplate
  
  centos:
    container_name: dc-boilerplate-centos
    restart: always
    build:
      context: centos
      args:
        UID: ${USER_ID:-1000}
        GID: ${GROUP_ID:-1000}
    working_dir: /var/www/dc-boilerplate
    volumes:
      - ../:/var/www/dc-boilerplate
